
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  safelist: ["dark"],
  prefix: "",
  
  content: [
    './pages/**/*.{ts,tsx,vue}',
    './components/**/*.{ts,tsx,vue}',
    './app/**/*.{ts,tsx,vue}',
    './src/**/*.{ts,tsx,vue}',
	],
  
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      height: {
        '0': '0vh',
        'px': '0.1vh',
        '0.5': '0.125vh',
        '1': '0.25vh',
        '1.5': '0.375vh',
        '2': '0.5vh',
        '2.5': '0.625vh',
        '3': '0.75vh',
        '3.5': '0.875vh',
        '4': '1vh',
        '5': '1.25vh',
        '6': '1.5vh',
        '7': '1.75vh',
        '8': '2vh',
        '9': '2.25vh',
        '10': '2.5vh',
        '11': '2.75vh',
        '12': '3vh',
        '14': '3.5vh',
        '16': '4vh',
        '20': '5vh',
        '24': '6vh',
        '28': '7vh',
        '32': '8vh',
        '36': '9vh',
        '40': '10vh',
        '44': '11vh',
        '48': '12vh',
        '52': '13vh',
        '56': '14vh',
        '60': '15vh',
        '64': '16vh',
        '72': '18vh',
        '80': '20vh',
        '96': '24vh',
      },
      fontSize: {
        'xs': ['1vh', '1.25vh'], 
        'sm': ['1.125vh', '1.5vh'],
        'base': ['1.25vh', '1.75vh'],
        'lg': ['1.5vh', '2vh'],
        'xl': ['1.875vh', '2.25vh'],
        '2xl': ['2.25vh', '2.5vh'],
        '3xl': ['3vh', '3.5vh'],
        '4xl': ['3.75vh', '4.25vh'],
        '5xl': ['4.5vh', '5vh'],
        '6xl': ['6vh', '6.5vh'],
        '7xl': ['7.5vh', '8vh'],
        '8xl': ['9vh', '10vh'],
        '9xl': ['12vh', '13vh'],
      },
      spacing: {
        '0': '0vh',
        'px': '0.1vh',
        '0.5': '0.125vh',
        '1': '0.25vh',
        '1.5': '0.375vh',
        '2': '0.5vh',
        '2.5': '0.625vh',
        '3': '0.75vh',
        '3.5': '0.875vh',
        '4': '1vh',
        '5': '1.25vh',
        '6': '1.5vh',
        '7': '1.75vh',
        '8': '2vh',
        '9': '2.25vh',
        '10': '2.5vh',
        '11': '2.75vh',
        '12': '3vh',
        '14': '3.5vh',
        '16': '4vh',
        '20': '5vh',
        '24': '6vh',
        '28': '7vh',
        '32': '8vh',
        '36': '9vh',
        '40': '10vh',
        '44': '11vh',
        '48': '12vh',
        '52': '13vh',
        '56': '14vh',
        '60': '15vh',
        '64': '16vh',
        '72': '18vh',
        '80': '20vh',
        '96': '24vh',
      },
      backdropBlur: {
        xs: '2px',
      },
      borderRadius: {
        DEFAULT: "0.5vh", 
        none: "0",
        sm: "0.3vh",
        md: "0.5vh",
        lg: "0.7vh",
        xl: "1vh",
        "2xl": "1.5vh",
        "3xl": "2vh",
        full: "5vh",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "collapsible-down": {
          from: { height: 0 },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        "collapsible-up": {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-in-out",
        "collapsible-up": "collapsible-up 0.2s ease-in-out",
      },
    },
  },
}